-- Q1. What is the total revenue generated by Male vs Female customers 
SELECT gender, SUM(purchase_amount) AS total_revenue FROM customer_trend_data_analysis.customer_trend_data_analysis
GROUP BY gender;
-- Q2. Which customer used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount FROM customer_trend_data_analysis.customer_trend_data_analysis
WHERE purchase_amount >=
(SELECT AVG(purchase_amount) FROM customer_trend_data_analysis.customer_trend_data_analysis)
AND discount_applied = 'Yes';
-- Q3. Which are top 5 products with the highest average review rating?
SELECT item_purchased, AVG(review_rating) AS "Average rating"
FROM customer_trend_data_analysis.customer_trend_data_analysis
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC 
LIMIT 5;

-- Q4. Compare the average purchase amounts between standard and express shipping 

SELECT shipping_type, ROUND(AVG(purchase_amount),2) AS avg_purchase_amount 
FROM customer_trend_data_analysis.customer_trend_data_analysis
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

SELECT subscription_status, 
COUNT(customer_id) AS No_of_customers,
ROUND(AVG(purchase_amount),2) AS Average_Spending, 
SUM(purchase_amount) AS Total_Spending 
FROM customer_trend_data_analysis.customer_trend_data_analysis
GROUP BY subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased, 
ROUND(COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE NULL END)/count(item_purchased)*100,2) AS Rate
FROM customer_trend_data_analysis.customer_trend_data_analysis
GROUP BY item_purchased
ORDER BY Rate DESC
LIMIT 5;  

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases,
-- and show the counts of each segment.
WITH Customer_Segment AS(SELECT customer_id, 
CASE WHEN previous_purchases = 1 THEN 'New'
WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
ELSE 'Loyal' end AS Customer_Segment
FROM customer_trend_data_analysis.customer_trend_data_analysis)
SELECT Customer_Segment,
COUNT(customer_id) AS No_customers
FROM Customer_Segment
GROUP BY Customer_Segment;

-- Q8. What are the top 3 most purchased products within each category?

WITH A AS (SELECT category,
item_purchased,
COUNT(*) AS Freq,
ROW_NUMBER() OVER ( 
PARTITION BY category
ORDER BY COUNT(*) DESC
) AS rn 
FROM customer_trend_data_analysis.customer_trend_data_analysis
GROUP BY category,
item_purchased)
SELECT category,
item_purchased,
Freq
FROM A 
WHERE rn <= 3;

-- Q9. Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
-- ANS. No
SELECT subscription_status,
COUNT(*) AS No_of_Customers
FROM customer_trend_data_analysis.customer_trend_data_analysis
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue distribution of each age group ?
SELECT age_group,
SUM(purchase_amount) AS Revenue
FROM customer_trend_data_analysis.customer_trend_data_analysis
GROUP BY age_group
ORDER BY Revenue DESC;
